from DIRECTORIES import FULL_USER_DIRECTORIES,PRESETS_DIR

def SET_PRESET():
    PRESETS = open(PRESETS_DIR, "w")
    
    DATA =  '{\n temperature_type = "C",\n pla:\n   {\n\t CELCIUS_BED_TEMPERATURE: 70,\n\t CELCIUS_TOOL_TEMPERATURE: 200,\n\t FAHRENHEIT_BED_TEMPERATURE: 158,\n\t FAHRENHEIT_TOOL_TEMPERATURE: 392\n   }\n}'
    
    PRESETS.write(DATA)